apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: e8ldew6xv-nodejs 
  janus-idp.io/tekton: e8ldew6xv-nodejs
  backstage.io/kubernetes-id: e8ldew6xv-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: e8ldew6xv-nodejs
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml