apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: e8ldew6xv-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: e8ldew6xv-nodejs 
  name: e8ldew6xv-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: e8ldew6xv-nodejs 
